import type {
  PersonaReview,
  AggregateData,
  CategoryAverage,
  Recommendation,
} from "./types";

export function generateMarkdownReport(
  url: string,
  reviews: PersonaReview[],
  aggregate: AggregateData
): string {
  const lines: string[] = [];

  lines.push("# Agentic First Review Report");
  lines.push("");
  lines.push(`**URL Reviewed:** ${url}`);
  lines.push(`**Date:** ${new Date().toLocaleDateString()}`);
  lines.push(`**Total Personas:** ${aggregate.totalReviews}`);
  lines.push("");

  lines.push("## Overall Score");
  lines.push("");
  lines.push(`**${aggregate.overallScore.toFixed(1)} / 10**`);
  lines.push("");

  lines.push("## Verdict Breakdown");
  lines.push("");
  const total =
    aggregate.verdictBreakdown.yes +
    aggregate.verdictBreakdown.maybe +
    aggregate.verdictBreakdown.no;
  if (total > 0) {
    lines.push(
      `- **Yes (Would Use):** ${aggregate.verdictBreakdown.yes} (${((aggregate.verdictBreakdown.yes / total) * 100).toFixed(1)}%)`
    );
    lines.push(
      `- **Maybe (With Changes):** ${aggregate.verdictBreakdown.maybe} (${((aggregate.verdictBreakdown.maybe / total) * 100).toFixed(1)}%)`
    );
    lines.push(
      `- **No (Would Not Use):** ${aggregate.verdictBreakdown.no} (${((aggregate.verdictBreakdown.no / total) * 100).toFixed(1)}%)`
    );
  }
  lines.push("");

  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score |");
  lines.push("|----------|-------|");
  const sorted = [...aggregate.categoryAverages].sort(
    (a: CategoryAverage, b: CategoryAverage) => b.averageScore - a.averageScore
  );
  for (const cat of sorted) {
    lines.push(`| ${cat.category} | ${cat.averageScore.toFixed(1)} / 10 |`);
  }
  lines.push("");

  if (aggregate.topRecommendations.length > 0) {
    lines.push("## Top Recommendations");
    lines.push("");
    aggregate.topRecommendations.forEach((rec: Recommendation, i: number) => {
      lines.push(`### ${i + 1}. [${rec.priority}] ${rec.title}`);
      lines.push("");
      lines.push(rec.description);
      lines.push(
        `*Mentioned by ${rec.mentionCount}/${rec.totalPersonas} personas*`
      );
      lines.push("");
    });
  }

  if (aggregate.audienceFit.length > 0) {
    lines.push("## Audience Fit");
    lines.push("");
    lines.push("| Segment | Fit Score | Recommendation |");
    lines.push("|---------|-----------|----------------|");
    for (const row of aggregate.audienceFit) {
      lines.push(
        `| ${row.segment} | ${row.fitScore.toFixed(1)} / 10 | ${row.recommendation} |`
      );
    }
    lines.push("");
  }

  lines.push("## Individual Persona Reviews");
  lines.push("");
  for (const review of reviews) {
    lines.push(`### ${review.personaName} (Wave ${review.waveNumber})`);
    lines.push("");
    lines.push(`**Background:** ${review.personaBackground}`);
    lines.push(
      `**Score:** ${review.overallScore}/10 | **Verdict:** ${review.verdict.toUpperCase()}`
    );
    lines.push("");
    lines.push(`**First Impression:** ${review.firstImpression}`);
    lines.push("");
    if (review.positives.length > 0) {
      lines.push("**Positives:**");
      review.positives.forEach((p: string) => lines.push(`- ${p}`));
      lines.push("");
    }
    if (review.concerns.length > 0) {
      lines.push("**Concerns:**");
      review.concerns.forEach((c: string) => lines.push(`- ${c}`));
      lines.push("");
    }
    lines.push(`**Top Praise:** ${review.topPraise}`);
    lines.push(`**Top Concern:** ${review.topConcern}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("");
  lines.push("*Generated by Agentic First Review*");

  return lines.join("\n");
}
