import type {
  PersonaReview,
  AggregateData,
  CategoryAverage,
  Recommendation,
} from "./types";

export function generateMarkdownReport(
  url: string,
  reviews: PersonaReview[],
  aggregate: AggregateData
): string {
  const lines: string[] = [];

  lines.push("# Agentic First Review Report");
  lines.push("");
  lines.push(`**URL Reviewed:** ${url}`);
  lines.push(`**Date:** ${new Date().toLocaleDateString()}`);
  lines.push(`**Total Personas:** ${aggregate.totalReviews}`);
  lines.push("");

  lines.push("## Overall Score");
  lines.push("");
  lines.push(`**${aggregate.overallScore.toFixed(1)} / 10**`);
  lines.push("");

  lines.push("## Verdict Breakdown");
  lines.push("");
  const total =
    aggregate.verdictBreakdown.yes +
    aggregate.verdictBreakdown.maybe +
    aggregate.verdictBreakdown.no;
  if (total > 0) {
    lines.push(
      `- **Yes (Would Use):** ${aggregate.verdictBreakdown.yes} (${((aggregate.verdictBreakdown.yes / total) * 100).toFixed(1)}%)`
    );
    lines.push(
      `- **Maybe (With Changes):** ${aggregate.verdictBreakdown.maybe} (${((aggregate.verdictBreakdown.maybe / total) * 100).toFixed(1)}%)`
    );
    lines.push(
      `- **No (Would Not Use):** ${aggregate.verdictBreakdown.no} (${((aggregate.verdictBreakdown.no / total) * 100).toFixed(1)}%)`
    );
  }
  lines.push("");

  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score |");
  lines.push("|----------|-------|");
  const sorted = [...aggregate.categoryAverages].sort(
    (a: CategoryAverage, b: CategoryAverage) => b.averageScore - a.averageScore
  );
  for (const cat of sorted) {
    lines.push(`| ${cat.category} | ${cat.averageScore.toFixed(1)} / 10 |`);
  }
  lines.push("");

  if (aggregate.topRecommendations.length > 0) {
    lines.push("## Top Recommendations");
    lines.push("");
    aggregate.topRecommendations.forEach((rec: Recommendation, i: number) => {
      lines.push(`### ${i + 1}. [${rec.priority}] ${rec.title}`);
      lines.push("");
      lines.push(rec.description);
      lines.push(
        `*Mentioned by ${rec.mentionCount}/${rec.totalPersonas} personas*`
      );
      lines.push("");
    });
  }

  if (aggregate.audienceFit.length > 0) {
    lines.push("## Audience Fit");
    lines.push("");
    lines.push("| Segment | Fit Score | Recommendation |");
    lines.push("|---------|-----------|----------------|");
    for (const row of aggregate.audienceFit) {
      lines.push(
        `| ${row.segment} | ${row.fitScore.toFixed(1)} / 10 | ${row.recommendation} |`
      );
    }
    lines.push("");
  }

  lines.push("## Individual Persona Reviews");
  lines.push("");
  for (const review of reviews) {
    lines.push(`### ${review.personaName} (Wave ${review.waveNumber})`);
    lines.push("");
    lines.push(`**Background:** ${review.personaBackground}`);
    lines.push(
      `**Score:** ${review.overallScore}/10 | **Verdict:** ${review.verdict.toUpperCase()}`
    );
    lines.push("");
    lines.push(`**First Impression:** ${review.firstImpression}`);
    lines.push("");
    if (review.positives.length > 0) {
      lines.push("**Positives:**");
      review.positives.forEach((p: string) => lines.push(`- ${p}`));
      lines.push("");
    }
    if (review.concerns.length > 0) {
      lines.push("**Concerns:**");
      review.concerns.forEach((c: string) => lines.push(`- ${c}`));
      lines.push("");
    }
    lines.push(`**Top Praise:** ${review.topPraise}`);
    lines.push(`**Top Concern:** ${review.topConcern}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("");
  lines.push("*Generated by Agentic First Review*");

  return lines.join("\n");
}

export function generatePlainTextReport(
  url: string,
  reviews: PersonaReview[],
  aggregate: AggregateData
): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split("T")[0];

  lines.push("WEBSITE REVIEW REPORT");
  lines.push(`URL: ${url}`);
  lines.push(`Date: ${date}`);
  lines.push(`Reviewed by: ${aggregate.totalReviews} AI agent personas`);
  lines.push("");

  lines.push(`OVERALL SCORE: ${aggregate.overallScore.toFixed(1)} / 10`);
  lines.push("");

  const vb = aggregate.verdictBreakdown;
  lines.push(`VERDICT: ${vb.yes} Yes | ${vb.maybe} Maybe | ${vb.no} No`);
  lines.push("");

  lines.push("CATEGORY SCORES:");
  const sorted = [...aggregate.categoryAverages].sort(
    (a: CategoryAverage, b: CategoryAverage) => b.averageScore - a.averageScore
  );
  for (const cat of sorted) {
    lines.push(`- ${cat.category}: ${cat.averageScore.toFixed(1)}/10`);
  }
  lines.push("");

  if (aggregate.topRecommendations.length > 0) {
    lines.push("TOP ISSUES TO FIX:");
    aggregate.topRecommendations.forEach((rec: Recommendation, i: number) => {
      lines.push(
        `${i + 1}. [${rec.priority}] ${rec.title} (mentioned by ${rec.mentionCount}/${rec.totalPersonas} agents)`
      );
      if (rec.description !== rec.title) {
        lines.push(`   ${rec.description}`);
      }
    });
    lines.push("");
  }

  // Collect praises from reviews
  const praises = reviews
    .filter((r) => r.topPraise)
    .map((r) => r.topPraise);
  if (praises.length > 0) {
    lines.push("WHAT'S WORKING WELL:");
    const uniquePraises = Array.from(new Set(praises)).slice(0, 10);
    for (const praise of uniquePraises) {
      lines.push(`- ${praise}`);
    }
    lines.push("");
  }

  if (aggregate.audienceFit.length > 0) {
    lines.push("AUDIENCE FIT:");
    for (const row of aggregate.audienceFit) {
      lines.push(
        `- ${row.segment}: ${row.fitScore.toFixed(1)}/10 -- ${row.recommendation}`
      );
    }
    lines.push("");
  }

  lines.push("DETAILED AGENT FEEDBACK:");
  lines.push("");
  for (const review of reviews) {
    lines.push(
      `--- ${review.personaName} (Score: ${review.overallScore}/10, Verdict: ${review.verdict.toUpperCase()}) ---`
    );
    lines.push(`First impression: ${review.firstImpression}`);
    if (review.positives.length > 0) {
      lines.push(`Positives: ${review.positives.join("; ")}`);
    }
    if (review.concerns.length > 0) {
      lines.push(`Concerns: ${review.concerns.join("; ")}`);
    }
    lines.push(`Top praise: ${review.topPraise}`);
    lines.push(`Top concern: ${review.topConcern}`);
    if (review.recommendation) {
      lines.push(`Recommendation: ${review.recommendation}`);
    }
    lines.push("");
  }

  lines.push("Generated by Agentic First Review");

  return lines.join("\n");
}
